/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2018-01-31 10:43:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.controller.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/login/form_header.jsp", Long.valueOf(1517354136377L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Match@Finder</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css\">\r\n");
      out.write("  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900|RobotoDraft:400,100,300,500,700,900'>\r\n");
      out.write("  <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<style>\r\n");
      out.write(".container{\r\n");
      out.write("   margin-top: 6%;\r\n");
      out.write("}\r\n");
      out.write("  .container-fluid {\r\n");
      out.write("      padding: 10px 30px;\r\n");
      out.write("  }\r\n");
      out.write("  .rerun{\r\n");
      out.write("   margin-top:7%;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"60\" style=\"background: url('bg1.jpg');\">\r\n");
      out.write("<nav class=\"navbar navbar-inner navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\"><a href=\"../index.jsp\"><img src=\"../pic/logos.png\" alt=\"logo\" style=\"float: left; margin-right: 20px \" height=\"50px\" width=\"50px\"></a>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"../index.jsp\">MatchFinder</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("       <li><a href=\"../index.jsp\">Home</a></li>\r\n");
      out.write("  <!--    <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Page 1 <span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"#\">Page 1-1</a></li>\r\n");
      out.write("          <li><a href=\"#\">Page 1-2</a></li>\r\n");
      out.write("          <li><a href=\"#\">Page 1-3</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>   -->\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("<!--      <li><a href=\"login/login.html\"><span class=\"glyphicon glyphicon-user\"></span> SignUp</a></li>\r\n");
      out.write("      <li><a href=\"login/login.html\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write(" -->   \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Mixins-->\n");
      out.write("<!-- Pen Title-->\n");
      out.write("<!--<div class=\"rerun\"><a href=\"\">Rerun Pen</a></div> -->\n");
      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"card\"></div>\n");
      out.write("  <div class=\"card\">\n");
 String msg=request.getParameter("msg"); if(msg!=null){

      out.write("\n");
      out.write("<h1 class=\"title\" style=\"font-size:14px\">\n");

out.print(msg+" !! Try Again.."); 
      out.write("</h1> ");
 }
      out.write("\n");
      out.write("    <h1 class=\"title\">Login</h1>\n");
      out.write("    <form action=\"../Login\" method=\"post\">\n");
      out.write("      <div class=\"input-container\">\n");
      out.write("        <input type=\"email\" id=\"#label\" name=\"email\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Email</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"input-container\">\n");
      out.write("        <input type=\"password\" name=\"password\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Password</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"button-container\">\n");
      out.write("        <button><span>Go</span></button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"footer\"><a href=\"forget.jsp\">Forgot your password?</a></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("  <!-- Ajax for checking new user existence in database -->\n");
      out.write("  <script>\n");
      out.write("  var mail = documen.getElementByName(\"mail\");\n");
      out.write("  var myForm = documen.getElementByName(\"myForm\");\n");
      out.write("  function ValidateEmail(mail) \n");
      out.write("  {\n");
      out.write("   if (/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$/.test(myForm.email.value))\n");
      out.write("    {\n");
      out.write("\t  function sendInfo();\n");
      out.write("      return (true);\n");
      out.write("    }\n");
      out.write("      document.getElementById(\"mailWarn\").innerHTML = \"Invalid email format\";\n");
      out.write("      return (false);\n");
      out.write("  }\n");
      out.write("  var request;\n");
      out.write("  function sendInfo()\n");
      out.write("  {\n");
      out.write("  var v=document.getElementByName('email').value; \n");
      out.write("  var url=\"../ValidateUser?val=\"+v;\n");
      out.write("  if(window.XMLHttpRequest){\n");
      out.write("  request=new XMLHttpRequest();\n");
      out.write("  }\n");
      out.write("  else if(window.ActiveXObject){\n");
      out.write("  request=new ActiveXObject(\"Microsoft.XMLHTTP\");\n");
      out.write("  }\n");
      out.write("  try{\n");
      out.write("  request.onreadystatechange=getInfo;\n");
      out.write("  request.open(\"POST\",url,true);\n");
      out.write("  request.send();\n");
      out.write("  }catch(e){alert(\"Unable to connect to server\");}\n");
      out.write("  }\n");
      out.write("  function getInfo(){\n");
      out.write("  if(request.readyState==4){\n");
      out.write("  var val=request.responseText;\n");
      out.write("  document.getElementById('valid').innerHTML=val;\n");
      out.write("  }}\n");
      out.write("\n");
      out.write("  function validatePassword() {\n");
      out.write("\n");
      out.write("\t\tvar pass = document.getElementById(\"password\").value;\n");
      out.write("\t\tvar cnfpass = document.getElementById(\"password2\").value;\n");
      out.write("\t   var msg = document.getElementById(\"warn\");     \t\n");
      out.write("\t\tif (pass != cnfpass) {\n");
      out.write("\t\t\t\t\tmsg.innerHTML = \"Passwords do not match.\"; \n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t    }\n");
      out.write("\t\telse\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\tmsg.innerHTML = \"\"; \n");
      out.write("\t\t\t\t\treturn true;\n");
      out.write("\t\t\t}\n");
      out.write("\t}\n");
      out.write(" </script>\n");
      out.write("  \n");
      out.write("  <div class=\"card alt\" style=\"background-color: #ed2553; margin-bottom: 10px;\">\n");
      out.write("    <div class=\"toggle\"></div>\n");
      out.write("    <h1 class=\"title\">Register\n");
      out.write("      <div class=\"close\"></div>\n");
      out.write("    </h1>\n");
      out.write("    <form action=\"../SignUp\" method=\"post\" name=\"myForm\" onsubmit=\"validatePassword()\">\n");
      out.write("      <div class=\"input-container\">\n");
      out.write("        <input type=\"text\" name=\"name\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Name</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"input-container\">\n");
      out.write("        <input type=\"text\" name=\"age_of_agent\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Age of Agent</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"input-container\">\n");
      out.write("        <input type=\"text\" name=\"age_of_business\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Age of Business</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"input-container\">\n");
      out.write("        <input type=\"email\" onchange=\"sendInfo()\" name=\"email\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Email</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"input-container\">\n");
      out.write("        <input type=\"text\" name=\"contact\" onkeypress=\"return event.charCode >= 48 && event.charCode <= 57\" maxlength=\"10\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Contact Number</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("     <div class=\"input-container\">\n");
      out.write("        <input type=\"text\" name=\"address\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Address</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("        <input id=\"lat\" type=\"hidden\" name=\"lat\" />\n");
      out.write("        <input id=\"lan\" type=\"hidden\" name=\"lan\" />\n");
      out.write("       <div class=\"input-container\">\n");
      out.write("        <input type=\"password\" id=\"password\" name=\"password\" onblur=\"validatePassword()\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Password</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"input-container\">\n");
      out.write("        <input type=\"password\" id=\"password2\" name=\"password2\" onkeyup=\"validatePassword()\" id=\"#label\" required=\"required\"/>\n");
      out.write("        <label for=\"#label\">Confirm Password</label>\n");
      out.write("        <div class=\"bar\"></div>\n");
      out.write("      </div>\n");
      out.write("        <p id=\"warn\" style=\"color:white; margin-bottom:10px; font-size:18px; letter-spacing:2px\"></p>\n");
      out.write("      <div class=\"button-container\">\n");
      out.write("        <button><span>Next</span></button>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write(" </div>\n");
      out.write(" \n");
      out.write(" <script>\n");
      out.write("var x = document.getElementById(\"lat\");\n");
      out.write("var y = document.getElementById(\"lan\");\n");
      out.write("getLocation();\n");
      out.write("function getLocation() {\n");
      out.write("    if (navigator.geolocation) {\n");
      out.write("        navigator.geolocation.getCurrentPosition(showPosition);\n");
      out.write("    } else {\n");
      out.write("        x.value = 28;\n");
      out.write("        y.value = 77;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("function showPosition(position) {\n");
      out.write("    x.value = position.coords.latitude;\n");
      out.write("    y.value = position.coords.longitude; \n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\n");
      out.write("<script src=\"js/index.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
