/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2018-02-01 02:50:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.controller.*;
import java.sql.*;
import com.classes.*;
import com.classes.*;
import java.sql.*;
import java.io.*;
import java.util.ArrayList;
import com.classes.*;

public final class agent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/agentsList.jsp", Long.valueOf(1517453453265L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1517441155097L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1517432919570L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
 HttpSession session = request.getSession(false); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Match@Finder</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#about{\r\n");
      out.write("\tcolor: rgb(0,0,0);\r\n");
      out.write("\tfont-size:22;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("#copy{\r\n");
      out.write("\tcolor:rgb(234,39,0);\r\n");
      out.write("\tfont-size: 32;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tletter-spacing: 2px;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write(" background: url('pic/11__11.jpg') no-repeat fixed;\r\n");
      out.write("  background-size: 100% 100%;\r\n");
      out.write("}\r\n");
      out.write("footer, #about{\r\n");
      out.write("background-color: rgba(255,255,255,0.2);\r\n");
      out.write("}\r\n");
      out.write("  .container {\r\n");
      out.write("      padding: 10px 30px;\r\n");
      out.write("  }\r\n");
      out.write("  .carousel-inner img {\r\n");
      out.write("    //  -webkit-filter: grayscale(90%);\r\n");
      out.write("   //  filter: grayscale(90%); /* make all photos black and white */ \r\n");
      out.write("      width: 100%; /* Set width to 100% */\r\n");
      out.write("     margin:auto;\r\n");
      out.write("  }\r\n");
      out.write("  .carousel-caption h3 {\r\n");
      out.write("      color: #fff !important;\r\n");
      out.write("  }\r\n");
      out.write("    @media (max-width: 600px) {\r\n");
      out.write("    .carousel-caption {\r\n");
      out.write("      display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */\r\n");
      out.write("    }\r\n");
      out.write("  }  \r\n");
      out.write("  #signal{\r\n");
      out.write("  \tfloat: right;\r\n");
      out.write("  \tmargin-top: 100px;\r\n");
      out.write("  }\r\n");
      out.write("  #upload_dp {\r\n");
      out.write("    display: none;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("}\r\n");
      out.write("   #dp1:hover {\r\n");
      out.write("    opacity: 0.5;\r\n");
      out.write("    filter: alpha(opacity=50); /* For IE8 and earlier */\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("  </style>\r\n");
      out.write("  <script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\"#dp1\").click(function(){\r\n");
      out.write("        $('#upload_dp').click();\r\n");
      out.write("    })\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"60\">\r\n");
      out.write("<nav class=\"navbar navbar-inner navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("    <a href=\"index.jsp\"><img src=\"pic/logos.png\" alt=\"logo\" style=\"float: left; margin-right: 20px \" height=\"50px\" width=\"50px\"></a>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\">MatchFinder</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("       <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("  <!--    <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Page 1 <span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("          <li><a href=\"#\">Page 1-1</a></li>\r\n");
      out.write("          <li><a href=\"#\">Page 1-2</a></li>\r\n");
      out.write("          <li><a href=\"#\">Page 1-3</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>   -->\r\n");
      out.write("     ");

      if(session!=null)
      { 
      out.write("\r\n");
      out.write("      <li><a href=\"agent.jsp\">Agents</a></li>\r\n");
      out.write("   ");
  if(session.getAttribute("user")!=""|session.getAttribute("user")!=null)    
       { UserBean user = (UserBean)session.getAttribute("user");
        if(user.getStatus()==0)
        {
       
      out.write("\r\n");
      out.write("      <li><a href=\"package.jsp\">Subscription</a></li>\r\n");
      out.write("      ");

       }
       }
      } 
      out.write("\r\n");
      out.write("      <li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("<script>\r\n");
      out.write("function upload(){\r\n");
      out.write("\t document.getElementById('upload').submit();\r\n");
      out.write("\t  }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("      ");

      if(session!=null)
      {
    	  if(session.getAttribute("user")!=null)
    	  {
    	    UserBean user = (UserBean)session.getAttribute("user");
    	    if(user!=null)
    	    {   
      out.write("\r\n");
      out.write("        <form action=\"UploadImage\" method=\"post\" id=\"upload\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <input id=\"upload_dp\" type=\"file\" name=\"dp\" size=\"chars\" onchange=\"document.getElementById('upload').submit();\">\r\n");
      out.write("           </form>\r\n");
      out.write("      <li style=\"font-size:20px; margin-top:10px;\">\r\n");
      out.write("      ");
      if(user.getDp()!=null)
               { int id = user.getId(); 
      out.write("\r\n");
      out.write("      <img id=\"dp1\" src=\"getImage.jsp?id=");
      out.print(id );
      out.write("\" class=\"img-circle\" alt=\"getDp\" style=\"margin-top:5px; margin-right:10px;\" width=\"40px\" hieght=\"40px\"></img></li><li><a style=\"text-decoration:none;\" href=\"profile.jsp?id=");
      out.print(user.getId() );
      out.write('"');
      out.write('>');
      out.print(user.getName() );
      out.write("</a></li>\r\n");
      out.write("      ");
         }
              else{ 
      out.write("\r\n");
      out.write("    \t<img id=\"dp1\" src=\"pic/businessman_17.png\" class=\"img-circle\" alt=\"DefaultDp\" style=\"margin-top:5px; margin-right:10px;\" width=\"40px\" hieght=\"40px\"></img><a style=\"text-decoration:none;\" href=\"profile.jsp?id=");
      out.print(user.getId() );
      out.write('"');
      out.write('>');
      out.print(user.getName() );
      out.write("</a></li>\r\n");
      out.write("      ");
         } 
             }
      
      out.write("\r\n");
      out.write("      <li><a href=\"SignOut\"><span class=\"glyphicon glyphicon-log-in\"></span> SignOut</a></li>\r\n");
      out.write("      ");
  } 
      else {
      out.write("\r\n");
      out.write("    \t\t<li><a href=\"login/login.jsp\"><span class=\"glyphicon glyphicon-user\"></span> SignUp</a></li>\r\n");
      out.write("    \t      <li><a href=\"login/login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> SignIn</a></li> \r\n");
      out.write("  ");
  } }
    else { 
      out.write("\r\n");
      out.write("    \t<li><a href=\"login/login.jsp\"><span class=\"glyphicon glyphicon-user\"></span> SignUp</a></li>\r\n");
      out.write("      <li><a href=\"login/login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> SignIn</a></li> \r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("       </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Header Closed -->>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<link href=\"agents/css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<script src=\"agents/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,500,700,200,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--start-body-->\r\n");
      out.write("\t\t\t<!--star-wrapper-demo-->\r\n");
      out.write("\t\t\t<div class=\"wrapper-demo\">\r\n");
      out.write("\t\t\t\t<h1>Agent List</h1>\r\n");
      out.write("\t\t\t\t<!--start-wrapper-dropdown-2-->\r\n");
      out.write("\t\t\t\t\t<div id=\"dd\" class=\"wrapper-dropdown-2 active\" tabindex=\"1\">Agents<i><img src=\"agents/images/menu.png\"/></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <!-- start search-->\r\n");
      out.write("\t\t\t\t    <div class=\"search-box\">\r\n");
      out.write("\t\t\t\t\t    <div id=\"sb-search\" class=\"sb-search\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"sb-search-input\" placeholder=\"Enter your search term...\" onkeyup=\"\" type=\"search\" name=\"search\" id=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"sb-search-submit\" type=\"submit\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sb-icon-search\"> </span>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <!-- search-scripts -->\r\n");
      out.write("\t\t\t\t\t<script src=\"agents/js/classie.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"agents/js/uisearch.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\tnew UISearch( document.getElementById( 'sb-search' ) );\r\n");
      out.write("\t\t\t\t\t\t\tfunction sendInfo(){\r\n");
      out.write("\t\t\t\t\t\t\t\t  var v=document.getElementById('search').value; \r\n");
      out.write("\t\t\t\t\t\t\t\t  var url=\"Agents?val=\"+v;\r\n");
      out.write("\t\t\t\t\t\t\t\t  alert(url);\r\n");
      out.write("\t\t\t\t\t\t\t\t  if(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\t\t\t\t\t   request=new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t  else if(window.ActiveXObject){\r\n");
      out.write("\t\t\t\t\t\t\t\t  request=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t  try{\r\n");
      out.write("\t\t\t\t\t\t\t\t  request.onreadystatechange=getInfo();\r\n");
      out.write("\t\t\t\t\t\t\t\t  request.open(\"GET\",url,true);\r\n");
      out.write("\t\t\t\t\t\t\t\t  request.send();\r\n");
      out.write("\t\t\t\t\t\t\t\t  }catch(e){alert(\"Unable to connect to server\");}\r\n");
      out.write("\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t  function getInfo(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  alert(\"getInf\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  if(request.readyState==4){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  alert(\"getInf readystat 4\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  var val=request.responseText;\r\n");
      out.write("\t\t\t\t\t\t\t\t  alert(\"getInf readystat 4 after val \"+val);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//  document.getElementById('valid').innerHTML=val;\r\n");
      out.write("\t\t\t\t\t\t\t\t  alert(val);\r\n");
      out.write("\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t  alert(\"getInf end out of if\");\r\n");
      out.write("\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<!-- /search-scripts -->\r\n");
      out.write(" \t\t\t\t<!-- end search-->\r\n");
      out.write(" \t\r\n");
      out.write(" \t");
 	
 	ArrayList<UserBean> all = new ArrayList<UserBean>();
 	ResultSet rs;
//	String search = request.getParameter("val");
    Connection con = (Connection) ConnectionCon.getConnection();
		try {
			Statement stm = (Statement) con.createStatement();
   //        rs = stm.executeQuery("select * from agents where ( concat(name,concat(email,concat(contact,address))) like '%"+ 
      out.write(" <script>document.write(document.getElementById(\"search\").value);</script> ");
 //"%')");			
		     rs = stm.executeQuery("select * from agents");			
		   while(rs.next()){
			   UserBean b = new UserBean();
			   b.setId(rs.getInt("agent_id"));
		    	b.setName(rs.getString("name"));
		    	b.setAge_of_agent(Integer.parseInt(rs.getString("age_of_agent")));
		    	b.setAge_of_Business(Integer.parseInt(rs.getString("age_of_business")));
		    	b.setEmail(rs.getString("email"));
		    	b.setAddress(rs.getString("address"));
		    	b.setPassword(rs.getString("password"));
		    	Blob blob = rs.getBlob("dp");
		        byte[] byteArray = blob.getBytes(1, (int)blob.length());
		     	b.setDp(byteArray);
		    	b.setSub_amt(rs.getInt("sub_amt"));
		    	b.setContact(Long.parseLong(rs.getString("contact")));
		    	b.setLat(Double.parseDouble(rs.getString("latitude")));
		    	b.setLan(Double.parseDouble(rs.getString("longitude")));
		    	b.setStatus(rs.getInt("status"));
		        b.setMsg("Sucessfully logged In ");
		        b.setUpdate(1);
		        all.add(b);
		        System.out.println("SuccessFull Ajax of agent.java");
		    }
		    session.setAttribute("all", all);
		 out.print("hello");    
	    } catch (SQLException e) {
	        System.out.println(e);
			 }
 
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t<ul class=\"dropdown\">\t\t\t\t\t\t\t\r\n");
  for(UserBean b : all){

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"friends-grids\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"grids-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"img-circle\" width=\"120px\" height=\"120px\" src=\"getImage.jsp?id=");
      out.print(b.getId() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"friend-grid\"><p class=\"flowers\">14k</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"grids-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2>");
      out.print(b.getName() );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t<img src=\"agents/images/heart.png\" /> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"grids-right-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"user\">");
      out.print(b.getAge_of_agent() );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"camera\">");
      out.print(b.getAge_of_Business() );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"chat\">");
      out.print(b.getId() );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");

}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--end-wrapper-dropdown-2-->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!--start-script-->\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tfunction DropDown(el) {\r\n");
      out.write("\t\t\t\t\t\t\t\tthis.dd = el;\r\n");
      out.write("\t\t\t\t\t\t\t\tthis.initEvents();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tDropDown.prototype = {\r\n");
      out.write("\t\t\t\t\t\t\t\tinitEvents : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar obj = this;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tobj.dd.on('click', function(event){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(this).toggleClass('active');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tevent.stopPropagation();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dd = new DropDown( $('#dd') );\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$(document).click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// all dropdowns\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('.wrapper-dropdown-2').removeClass('active');\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<!--end-script-->\r\n");
      out.write("\t\t\t<!--end-wrapper-demo-->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<!-- Footer Start -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"container-fluid text-center\" style=\"float:bottom;\">\r\n");
      out.write("  <a href=\"#myPage\" title=\"To Top\">\r\n");
      out.write("    <span class=\"glyphicon glyphicon-chevron-up\"></span>\r\n");
      out.write("  </a>\r\n");
      out.write("  <p id=\"copy\">&copyCopyright  <a href=\"https://www.matchfinder.online\" title=\"Visit MatchFinder\">www.matchfinder.online</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("  // Add smooth scrolling to all links in navbar + footer link\r\n");
      out.write("  $(\".navbar a, footer a[href='#myPage']\").on('click', function(event) {\r\n");
      out.write("    // Make sure this.hash has a value before overriding default behavior\r\n");
      out.write("    if (this.hash !== \"\") {\r\n");
      out.write("      // Prevent default anchor click behavior\r\n");
      out.write("      event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("      // Store hash\r\n");
      out.write("      var hash = this.hash;\r\n");
      out.write("\r\n");
      out.write("      // Using jQuery's animate() method to add smooth page scroll\r\n");
      out.write("      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area\r\n");
      out.write("      $('html, body').animate({\r\n");
      out.write("        scrollTop: $(hash).offset().top\r\n");
      out.write("      }, 900, function(){\r\n");
      out.write("   \r\n");
      out.write("        // Add hash (#) to URL when done scrolling (default click behavior)\r\n");
      out.write("        window.location.hash = hash;\r\n");
      out.write("      });\r\n");
      out.write("    } // End if\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  $(window).scroll(function() {\r\n");
      out.write("    $(\".slideanim\").each(function(){\r\n");
      out.write("      var pos = $(this).offset().top;\r\n");
      out.write("\r\n");
      out.write("      var winTop = $(window).scrollTop();\r\n");
      out.write("        if (pos < winTop + 600) {\r\n");
      out.write("          $(this).addClass(\"slide\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<!-- Footer End -->\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
